services:
  - type: web
    name: plantech-erp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
